# Generated by Django 5.0.7 on 2024-08-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAPI', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.CharField(default='dami', max_length=50),
        ),
    ]
