# Generated by Django 5.0.7 on 2024-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAPI', '0004_user_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=4000),
        ),
    ]
